apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
- ../../rollouts-base
- infrastructure.yaml
- frontend-rollout.yaml
- ingress.yaml

# tutaj trzeba będzie zmienić na target kind Rollout pewnie.
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value: [{ name: github }]
    - op: add
      path: /spec/progressDeadlineSeconds
      value: 60
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=booking-microservices

